### ISSUE TITLE
Exceptions are not passed

### ISSUE THREAD

**Issue by icanhazpython** [powercode/PSParallel#10]
Not sure how I overlooked this before, but exceptions are not passed back from the scriptblock in any way.
The below example code does not present any exceptions.
`@(2, 3) | invoke-parallel { throw "test" }`

**Comment by powercode** [comment]
Do you think you can make a PR with failing pester tests?

**Comment by icanhazpython** [comment]
I think this is an inherent issue with runspaces; I read somewhere else that PS runspaces do not allow exceptions to escape the runspace. So I suppose this would not normally be possible.
