### ISSUE TITLE
Parameters -ImportModule -ImportVariable are missing

### ISSUE THREAD

**Issue by variableresistor** [powercode/PSParallel#5]
The help for Invoke Parallel states that the -ImportModule and -ImportVariable switch parameters can be used to import the modules in the current session as well as the variables:
DESCRIPTION
The cmdlet uses a RunspacePool an and invokes the provied scriptblock once for each input.

To control the environment of the scriptblock, the ImportModule, ImportVariable and ImportFunction parameters can be used.

However, these parameters are missing from the list of parameters and are not listed in the parameter list. Also, it looks like "provied" is misspelled. (Just to nitpick)

**Comment by ITGuyOU** [comment]
For reference, the .ps1 version on Invoke-Parallel is here:
https://github.com/RamblingCookieMonster/Invoke-Parallel
