### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by erikgraa** [powercode/PSParallel#6]
Hi

Having some trouble using "Invoke-Parallel"

E.g. 

1..5 | Invoke-Parallel -ScriptBlock { $_ }

I get this:

Invoke-Parallel: Could not load type 'System.Management.AUtomation.InformationRecord' from assembly 'System.Management.Automation, Version=3.0.0, Culture=neutral, PublicKeyToken=...'.

Is it related to .NET perhaps?

Windows Server 2012 R2, 
PowerShell 4.0

**Comment by powercode** [comment]
What is the output of 
`$PSVersionTable` ?

And 
```powershell
Import-Module $PsParallel 
$error[0] | fl * -force -showerror
```

**Comment by erikgraa** [comment]
Hi

Seems to be working after I upgraded to WMF 5.1!

Tack

**Comment by powercode** [comment]
Maybe I have an old module manifest. Probably only tested on newer powershells.
